# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 00:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_history', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
